server:
    port: 9527

spring:
    application:
        name: cloud-gateway #以微服务注册进consul或nacos服务列表内
    cloud:
        consul: #配置consul地址
            host: localhost
            port: 8500
            discovery:
                prefer-ip-address: true
                service-name: ${spring.application.name}
        gateway:
            routes:
                -   id: pay-gateway-filter
                    uri: lb://cloud-provider-payment
                    predicates:
                        #                        - Path=/aaa/{placeholder}
                        - Path=/pay/gateway/filter
                    filters:
                        - My=atguigu
                    #                        - AddRequestHeader=X-Request-atguigu1,atguiguValue1 # 请求头
                    #                        - AddRequestHeader=X-Request-atguigu2,atguiguValue2
                    #                        - RemoveRequestHeader=user-agent      # 删除请求头，这里以user-agent为例
                    #                        - SetRequestHeader=sec-fetch-mode, Blue-updatebyzzyy # 将请求头sec-fetch-mode对应的值修改为Blue-updatebyzzyy
                    #                        - AddRequestParameter=addTestParameter,9999 # 增
                    #                        - RemoveRequestParameter=username # 删

                    #                         - AddResponseHeader=addResponseHeader,111
                    #                         - SetResponseHeader=Date,2099-11-11
                    #                         - RemoveResponseHeader=Content-Type
#                        - SetPath=/gateway/{placeholder}
#                        - PrefixPath=/pay
#                        - RedirectTo=302, https://www.baidu.com




#                -   id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#                    uri: lb://cloud-provider-payment                #匹配后提供服务的路由地址
#                    predicates:
#                        - Path=/pay/gateway/info              # 断言，路径相匹配的进行路由
#                        - My=diamond
#                        -   name: My
#                            args:
#                                userType: diamond


#                -   id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#                    uri: lb://cloud-provider-payment               #匹配后提供服务的路由地址
#                    predicates:
#                        - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
